### ISSUE TITLE
是否考虑支持Mirai

### ISSUE THREAD

**Issue by GreenChennai** [miaoscraft/SiS#11]
是否能考虑支持Mirai
如果能有Dll和Json的话....

**Comment by BaiMeow** [comment]
你只需要clone然后双击build.bat你就能编译出dll顺便生成出json了

**Comment by GreenChennai** [comment]
说的是一键构建
但是环境配置能要了我半条老命qwq

不过最后是可以的就很好

**Comment by GreenChennai** [comment]
[sis.zip](https://github.com/miaoscraft/SiS/files/5146311/sis.zip)

**Comment by Tnze** [comment]
> 说的是一键构建
> 但是环境配置能要了我半条老命qwq

不就是把这两个东西下下来一路Next就装好了嘛qwq。
![image](https://user-images.githubusercontent.com/19628575/91654339-68307e00-eada-11ea-9297-5ad517bf0507.png)
