### ISSUE TITLE
rcon返回数据为空

### ISSUE THREAD

**Issue by myktw** [miaoscraft/SiS#6]
执行指令RCON返回:""
错误：消息不支持或为空(-3)
只能执行help其他的gc，list什么的都不可以

**Comment by Tnze** [comment]
请提供完整的日志，还有配置文件等

**Comment by myktw** [comment]
![Snipaste_2019-11-19_22-06-10](https://user-images.githubusercontent.com/35424096/69153231-d2160300-0b18-11ea-94a0-0d4074110070.png)
![Snipaste_2019-11-19_21-47-08](https://user-images.githubusercontent.com/35424096/69153120-9844fc80-0b18-11ea-8ca9-27f0070fcada.png)
![Snipaste_2019-11-19_22-04-35](https://user-images.githubusercontent.com/35424096/69153130-9b3fed00-0b18-11ea-94dc-3c7953210c82.png)
服务器控制台正常发出信息机器人收不到
使用的是catserver核心cmi插件的命令

希望能命令能后面附带参数

**Comment by Tnze** [comment]
rcon配置好了吗
```
[RCON] # RCON配置
Address = "127.0.0.1:25575" #服务器地址:端口，必须写上端口
Password = "rcon_password"
```
https://github.com/miaoscraft/SiS/wiki/%E9%85%8D%E7%BD%AEMC%E6%9C%8D%E5%8A%A1%E5%99%A8%EF%BC%88RCON%EF%BC%89

**Comment by myktw** [comment]
rcon配置正常可以正常添加白名单和执行help命令
命令可以正常传输到服务器但是服务器无法返回数据给机器人
![Snipaste_2019-11-20_11-21-45](https://user-images.githubusercontent.com/35424096/69206601-1391c700-0b88-11ea-8085-b12f88dd7cc0.png)

**Comment by Tnze** [comment]
可能需要进一步测试。
RCON协议规定并非一个命令只能返回一条字符串，而是可能返回很多条。
但是当前SiS实现只发送服务端返回的第一条字符串。

可以尝试用其他RCON管理软件试一下你的服务端的RCON功能是否完全？
