### ISSUE TITLE
希望增加功能

### ISSUE THREAD

**Issue by myktw** [miaoscraft/SiS#7]
希望能在群里命令后面可以带参数执行

**Comment by Tnze** [comment]
我想讨论一下这么做是否存在指令注入的危险？

**Comment by myktw** [comment]
像禁用命令回显那样控制开关来允许部分指令能带参数运行可以吗？

**Comment by Tnze** [comment]
你想带参数运行什么指令呢？

**Comment by myktw** [comment]
比如部分指令有带玩家id的

**Comment by Tnze** [comment]
我觉得可以，等我有时间了就做。或者等一个pr😏

**Comment by Tnze** [comment]
代码提交上去了，但是暂时来不及打包发布更新，甚至修改之后还没测试。  
如果你想体验的话可以从[这里](https://ci.appveyor.com/project/Tnze/sis/builds/29106130/artifacts)下载未打包版本的插件。  
如果确认功能正常请告知我谢谢🙏，如果不能正常使用的话……自然也请告诉我😂

**Comment by myktw** [comment]
cn.miaoscraft.sis.dll加载失败! 错误: 不是合法的应用(LoadLibrary 失败,GetLastError=126)(-103)

**Comment by Tnze** [comment]
不应该啊，难道是ci的问题？
我暂时比较忙，请等我一段时间再看

**Comment by Amazefcc233** [comment]
```
[Cmd.say]
Level = 0
Command = "say"
AllowArgs = true
```
Q群: @ robot say
CoolQlog: 
 - 成员10001以等级0执行指令"say"
 - RCON返回: "Unknown command/say<--[HERE]"
mclog: 
 - say

Q群: @ robot say yo
CoolQlog:
 - 成员10001以等级0执行指令"say"
 - RCON返回: "Unknown command. Type \"/help\" for help.\n"
mclog:
 - sayyo

Q群: @ robot say yo ho
CoolQlog:
 - 成员10001以等级0执行指令"say"
 - RCON返回: "Unknown command. Type \"/help\" for help.\n"
mclog:
 - sayyo ho

@Tnze 存在bug，继续修吧= =~~（说白就是没加空格）~~

**Comment by Tnze** [comment]
修了，还有问题的话请再艾特我
