### ISSUE TITLE
CI下载的app.dll提示不合法应用

### ISSUE THREAD

**Issue by myktw** [miaoscraft/SiS#8]
![Snipaste_2019-11-30_22-19-55](https://user-images.githubusercontent.com/35424096/69901652-93f1cc80-13bf-11ea-9a1e-3c5e226462cc.png)
是我打开的方式不对吗

**Comment by Tnze** [comment]
不知道

**Comment by xxs-2** [comment]
不知道

**Comment by Amazefcc233** [comment]
不知道

**Comment by Tnze** [comment]
可能是你下载的那个版本刚好是我修改的时候不能正常编译的版本。
可以试试现在最新的

**Comment by Tnze** [comment]
由于没有能够复现这个问题，提问者也没有提供更多的信息，且长时间没有更多讨论，关闭这个issue吧。

**Comment by Tnze** [comment]
是由于CI使用的gcc编译出来的程序依赖的C语言运行时环境在电脑上未安装。
已通过编译参数`-static-libgcc`和`-static`静态编译C库
